import { test, expect, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'

async function sample(page:Page) {
  await page.goto('/')
  await page.getByRole('button',{name:'Explore a sample farm',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Every season, a clearer plan.'})).toBeVisible()
}
async function nav(page:Page, name:string) {
  const navigation=page.getByRole('navigation',{name:(page.viewportSize()?.width??1440)>800?'Main navigation':'Mobile navigation',exact:true})
  await expect(navigation).toBeVisible()
  await navigation.getByRole('link',{name,exact:true}).click()
}
async function expense(page:Page, name:string, amount:string) {
  await nav(page,'Expenses')
  await page.getByRole('button',{name:'Add expense',exact:true}).first().click()
  const dialog=page.getByRole('dialog')
  await dialog.getByLabel('Expense name',{exact:true}).fill(name)
  await dialog.getByLabel('Amount paid or valued (₱)',{exact:false}).fill(amount)
  await dialog.getByRole('button',{name:'Save expense',exact:true}).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('cell',{name:new RegExp(name)}).first()).toBeVisible()
}

test('sample dashboard, all pages, and both theme states',async({page},info)=>{
  const errors:string[]=[]; page.on('pageerror',e=>errors.push(e.message))
  await sample(page)
  await expect(page.locator('.metric-value').nth(0)).toHaveText('₱54,000.00')
  await expect(page.locator('.metric-value').nth(3)).toHaveText('₱8.13/ kg')
  await page.screenshot({path:info.outputPath('desktop-light.png'),fullPage:true})
  await page.getByRole('button',{name:'Close rice grain · switch to dark mode'}).press('Enter')
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark')
  await expect(page.locator('.theme-grain')).toHaveClass(/closed/)
  await page.screenshot({path:info.outputPath('desktop-dark.png'),fullPage:true})
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark')
  await page.getByRole('button',{name:'Open rice grain · switch to light mode'}).press('Space')
  await expect(page.locator('html')).toHaveAttribute('data-theme','light')
  for(const name of ['My budget','Expenses','Scenarios','Reports']) {await nav(page,name); await expect(page.locator('h1')).toBeVisible()}
  expect(errors).toEqual([])
})

test('real season is separate, sacks convert, unknown budgets stay incomplete',async({page})=>{
  await sample(page)
  await page.getByRole('button',{name:'New season',exact:true}).click()
  const d=page.getByRole('dialog')
  await d.getByLabel('Farm nickname').fill('QA Farm')
  await d.getByLabel('Season name',{exact:true}).fill('QA wet season')
  await d.getByLabel('Farm area (hectares)').fill('1.5')
  await d.getByLabel('Expected harvest',{exact:true}).fill('80')
  await d.getByLabel('Harvest unit').selectOption('sacks')
  await d.getByLabel('Kilograms per sack',{exact:false}).fill('50')
  await d.getByLabel('Assumed selling price (₱/kg)').fill('20')
  await d.getByRole('button',{name:'Save season',exact:true}).click()
  await expect(d).toHaveCount(0)
  await expect(page.getByText('My records',{exact:true})).toBeVisible()
  await expect(page.locator('.outlook-list')).toContainText('4,000')
  await expect(page.locator('.metric-value').nth(3)).toHaveText('—/ kg')
  await nav(page,'My budget')
  await expect(page.getByText('Known items only',{exact:true})).toHaveCount(2)
  await page.getByRole('button',{name:'Edit Seeds',exact:true}).click()
  await page.getByRole('dialog').getByLabel('Planned amount (₱)',{exact:false}).fill('0')
  await page.getByRole('button',{name:'Save planned cost',exact:true}).click()
  await expect(page.getByRole('row').filter({has:page.getByRole('button',{name:'Edit Seeds',exact:true})})).toContainText('₱0.00')
  await page.reload()
  await expect(page.getByLabel('Active season')).toContainText('QA wet season')
  await expect(page.getByLabel('Active season').locator('option')).toHaveCount(2)
})

test('expense save, editing, unknown and zero survive reload',async({page})=>{
  await sample(page)
  await expense(page,'QA fuel','123.45')
  await page.reload()
  const row=page.getByRole('row').filter({has:page.getByRole('button',{name:'Edit QA fuel',exact:true})})
  await expect(row).toContainText('₱123.45')
  await page.getByRole('button',{name:'Edit QA fuel',exact:true}).click()
  await page.getByRole('dialog').getByLabel('Amount paid or valued (₱)',{exact:false}).fill('')
  await page.getByRole('button',{name:'Save expense',exact:true}).click()
  await expect(row).toContainText('—')
  await page.getByRole('button',{name:'Edit QA fuel',exact:true}).click()
  await page.getByRole('dialog').getByLabel('Amount paid or valued (₱)',{exact:false}).fill('0')
  await page.getByRole('button',{name:'Save expense',exact:true}).click()
  await expect(row).toContainText('₱0.00')
})

test('scenario saves a frozen baseline without changing expenses',async({page})=>{
  await sample(page);await nav(page,'Scenarios')
  await page.getByLabel('Scenario name').fill('QA ten percent')
  await expect(page.locator('.scenario-highlight strong')).toHaveText('₱108,500.00')
  await page.getByRole('button',{name:'Save this scenario',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Saved possibilities'})).toBeVisible()
  await nav(page,'My budget')
  await page.getByRole('button',{name:'Edit Certified seed',exact:true}).click()
  await page.getByRole('dialog').getByLabel('Planned amount (₱)',{exact:false}).fill('9000')
  await page.getByRole('button',{name:'Save planned cost',exact:true}).click()
  await nav(page,'Scenarios')
  await page.getByRole('button',{name:/^QA ten percent Saved baseline/}).click()
  await expect(page.locator('.scenario-highlight strong')).toHaveText('₱108,500.00')
  await nav(page,'Overview')
  await expect(page.locator('.metric-value').nth(1)).toHaveText('₱54,000.00')
})

test('partial and final receipts use rounded sale value, never production value',async({page})=>{
  await sample(page); await nav(page,'Reports')
  await page.getByRole('button',{name:'Add sale',exact:true}).first().click()
  let d=page.getByRole('dialog')
  await d.getByLabel('Buyer (optional)').fill('QA buyer')
  await d.getByLabel('Quantity sold (kg)').fill('100.25')
  await d.getByLabel('Agreed price per kg (₱)').fill('20.50')
  await d.getByRole('button',{name:'Save sale',exact:true}).click()
  await page.getByRole('button',{name:'Add receipt',exact:true}).click()
  d=page.getByRole('dialog'); await d.getByLabel('Amount received (₱)').fill('1000')
  await d.getByRole('button',{name:'Save receipt',exact:true}).click()
  const row=page.getByRole('row').filter({hasText:'QA buyer'})
  await expect(row).toContainText('₱1,055.13')
  await page.getByRole('button',{name:'Add receipt',exact:true}).click()
  await page.getByRole('dialog').getByLabel('Amount received (₱)').fill('1055.13')
  await page.getByRole('button',{name:'Save receipt',exact:true}).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(row).toContainText('₱0.00')
  await page.getByRole('button',{name:'Add receipt',exact:true}).click()
  await page.getByRole('dialog').getByLabel('Amount received (₱)').fill('0.01')
  await page.getByRole('button',{name:'Save receipt',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('exceed')
})

test('backup download, invalid rejection and restore copies',async({page})=>{
  await sample(page); await nav(page,'Reports')
  const pending=page.waitForEvent('download')
  await page.getByRole('button',{name:'Download backup',exact:true}).click()
  const downloaded=await pending; const path=await downloaded.path(); expect(path).toBeTruthy()
  const buffer=await readFile(path!)
  const original=JSON.parse(buffer.toString()); expect(original.data.expenses).toHaveLength(8)
  await page.locator('#restore-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":999}')})
  await expect(page.getByRole('alert')).toContainText('not a valid')
  await page.locator('#restore-file').setInputFiles({name:'valid.json',mimeType:'application/json',buffer})
  await expect(page.getByText('Restore preview',{exact:false})).toBeVisible()
  page.once('dialog',dialog=>dialog.accept())
  await page.getByRole('button',{name:'Restore this backup',exact:true}).click()
  await expect(page.getByLabel('Active season').locator('option')).toHaveCount(2)
  await page.reload()
  await expect(page.getByLabel('Active season').locator('option')).toHaveCount(2)
})

test('mobile Filipino layout, theme and reduced motion',async({page},info)=>{
  await page.setViewportSize({width:390,height:844})
  await page.emulateMedia({reducedMotion:'reduce'})
  await sample(page)
  await page.screenshot({path:info.outputPath('mobile-light.png'),fullPage:true})
  await page.getByRole('button',{name:'Switch to Filipino'}).click()
  await expect(page.locator('html')).toHaveAttribute('lang','fil')
  await expect(page.getByRole('heading',{name:'Mas malinaw na plano sa bawat taniman.'})).toBeVisible()
  await page.getByRole('button',{name:'Isara ang palay · madilim na mode'}).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark')
  await page.screenshot({path:info.outputPath('mobile-dark-filipino.png'),fullPage:true})
  for(const name of ['Badyet','Mga gastos','Mga sitwasyon','Mga ulat']) {
    await page.getByRole('navigation',{name:'Nabigasyon sa mobile'}).getByRole('link',{name,exact:true}).click()
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  }
  expect(await page.locator('.rice-lid').evaluate(el=>getComputedStyle(el).transitionDuration)).toBe('0s')
  await page.reload(); await expect(page.locator('html')).toHaveAttribute('lang','fil')
})

test('cached app reloads offline and saves a new expense',async({page,context})=>{
  await sample(page)
  await page.evaluate(async()=>{await navigator.serviceWorker.ready})
  await page.reload()
  await expect.poll(()=>page.evaluate(()=>navigator.serviceWorker.controller!==null)).toBe(true)
  await context.setOffline(true)
  await page.reload()
  await expect(page.getByRole('heading',{name:'Every season, a clearer plan.'})).toBeVisible()
  await expense(page,'QA offline expense','300')
  await page.reload()
  await expect(page.getByRole('row').filter({hasText:'QA offline expense'})).toContainText('₱300.00')
  await context.setOffline(false)
})

test('restore on a fresh device accepts a season with unknown dates',async({page})=>{
  await page.goto('/')
  await page.getByRole('button',{name:'Plan my first season',exact:true}).click()
  const d=page.getByRole('dialog')
  await d.getByLabel('Farm nickname').fill('No dates farm')
  await d.getByLabel('Season name',{exact:true}).fill('Dates still unknown')
  await d.getByRole('button',{name:'Save season',exact:true}).click()
  await nav(page,'Reports')
  const pending=page.waitForEvent('download')
  await page.getByRole('button',{name:'Download backup',exact:true}).click()
  const downloaded=await pending; const buffer=await readFile((await downloaded.path())!)
  const newContext=await page.context().browser()!.newContext({viewport:{width:1440,height:1050}})
  const fresh=await newContext.newPage()
  await fresh.goto('http://127.0.0.1:4173')
  await fresh.getByRole('button',{name:'Restore a backup',exact:true}).click()
  await fresh.locator('#welcome-restore').setInputFiles({name:'season.json',mimeType:'application/json',buffer})
  await expect(fresh.getByRole('dialog')).toContainText('1 farms · 1 seasons · 0 expenses')
  await fresh.getByRole('button',{name:'Restore these records',exact:true}).click()
  await expect(fresh.getByRole('heading',{name:'Dates still unknown',exact:true})).toBeVisible()
  await expect(fresh.locator('.hero-copy')).toContainText('— hectares')
  await newContext.close()
})

test('failed local save preserves typed expense and shows failure',async({page})=>{
  await sample(page);await nav(page,'Expenses')
  await page.getByRole('button',{name:'Add expense',exact:true}).first().click()
  const d=page.getByRole('dialog')
  await d.getByLabel('Expense name',{exact:true}).pressSequentially('Unsaved fuel')
  await d.getByLabel('Amount paid or valued (₱)',{exact:false}).fill('75.25')
  await page.evaluate(()=>{IDBObjectStore.prototype.put=function(){throw new DOMException('Test quota reached','QuotaExceededError')}})
  await d.getByRole('button',{name:'Save expense',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('Could not save')
  await expect(d.getByLabel('Expense name',{exact:true})).toHaveValue('Unsaved fuel')
  await expect(d.getByLabel('Amount paid or valued (₱)',{exact:false})).toHaveValue('75.25')
})

test('season archive and copied budget keep old expense records separate',async({page})=>{
  await page.goto('/')
  await page.getByRole('button',{name:'Plan my first season',exact:true}).click()
  const d=page.getByRole('dialog')
  await d.getByLabel('Farm nickname').fill('Continuity farm')
  await d.getByLabel('Season name',{exact:true}).fill('First season')
  await d.getByRole('button',{name:'Save season',exact:true}).click()
  await expense(page,'First season fuel','99')
  await page.getByRole('button',{name:'New season',exact:true}).click()
  await d.getByLabel('Season name',{exact:true}).fill('Second season')
  await d.getByLabel('Copy a previous budget').selectOption({label:'First season'})
  await d.getByRole('button',{name:'Save season',exact:true}).click()
  await nav(page,'Expenses');await expect(page.getByRole('heading',{name:'No expenses yet'})).toBeVisible()
  await page.getByRole('button',{name:'Settings & storage',exact:true}).click()
  page.once('dialog',dialog=>dialog.accept())
  await page.getByRole('button',{name:'Archive First season',exact:true}).click()
  await expect(page.getByRole('button',{name:'Unarchive',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Unarchive',exact:true}).click()
  await page.getByRole('dialog').getByRole('button',{name:'Close / Isara'}).click()
  await page.getByLabel('Active season').selectOption({label:'Continuity farm · First season'})
  await expect(page.getByRole('row').filter({hasText:'First season fuel'})).toContainText('₱99.00')
})

test('rapid repeated receipt submission records only one payment',async({page})=>{
  await sample(page); await nav(page,'Reports')
  await page.getByRole('button',{name:'Add sale',exact:true}).first().click()
  const d=page.getByRole('dialog')
  await d.getByLabel('Quantity sold (kg)').fill('100')
  await d.getByLabel('Agreed price per kg (₱)').fill('20')
  await d.getByRole('button',{name:'Save sale',exact:true}).click()
  await page.getByRole('button',{name:'Add receipt',exact:true}).click()
  await d.getByLabel('Amount received (₱)').fill('2000')
  await d.locator('form').evaluate(form=>{form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}))})
  await expect(d).toHaveCount(0)
  const pending=page.waitForEvent('download')
  await page.getByRole('button',{name:'Download backup',exact:true}).click()
  const backup=JSON.parse((await readFile((await (await pending).path())!)).toString())
  expect(backup.data.receipts).toHaveLength(1)
  expect(backup.data.receipts[0].amount).toBe('2000')
})

test('changing harvest condition preserves the entered price condition',async({page})=>{
  await sample(page)
  await page.getByRole('button',{name:'View season details',exact:true}).click()
  const d=page.getByRole('dialog')
  await expect(d.getByLabel('Price applies to')).toHaveValue('fresh')
  await d.getByLabel('Harvest condition').selectOption('dried')
  await expect(d.getByLabel('Price applies to')).toHaveValue('fresh')
  await expect(d).toContainText('Harvest and price conditions do not match.')
  await d.getByRole('button',{name:'Save season',exact:true}).click()
  await expect(d).toHaveCount(0)
  await expect(page.locator('.metric-value').nth(3)).toHaveText('—/ kg')
  await page.reload()
  await page.getByRole('button',{name:'View season details',exact:true}).click()
  await expect(d.getByLabel('Harvest condition')).toHaveValue('dried')
  await expect(d.getByLabel('Price applies to')).toHaveValue('fresh')
})
