import { expect, test, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'

async function sample(page: Page) {
  await page.goto('/')
  await page.getByRole('button', { name: 'Explore a sample farm', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Every season, a clearer plan.' })).toBeVisible()
  await page.getByRole('button', { name: 'Dismiss', exact: true }).click()
}

async function nav(page: Page, name: string, language: 'en' | 'fil' = 'en') {
  const mobile = (page.viewportSize()?.width ?? 1440) <= 800
  const navigation = language === 'fil'
    ? (mobile ? 'Nabigasyon sa mobile' : 'Pangunahing nabigasyon')
    : (mobile ? 'Mobile navigation' : 'Main navigation')
  await page.getByRole('navigation', { name: navigation, exact: true }).getByRole('link', { name, exact: true }).click()
}

function discardDialog(page: Page) {
  return page.getByRole('dialog', { name: 'Discard unsaved changes?', exact: true })
}

test('Overview opens an expense form immediately and saves into the expense log', async ({ page }) => {
  await sample(page)
  await page.getByRole('button', { name: 'Add expense', exact: true }).click()
  const form = page.getByRole('dialog', { name: 'Add expense', exact: true })
  await expect(form).toBeVisible()
  await expect(page).toHaveURL(/#expenses$/)
  await form.getByLabel('Expense name', { exact: true }).fill('Quick entry transport')
  await form.getByLabel('Amount paid or valued (₱)', { exact: false }).fill('125.50')
  await form.getByRole('button', { name: 'Save expense', exact: true }).click()
  await expect(form).toHaveCount(0)
  await expect(page.getByRole('row').filter({ hasText: 'Quick entry transport' })).toContainText('₱125.50')
  await page.reload()
  await expect(page.getByRole('row').filter({ hasText: 'Quick entry transport' })).toContainText('₱125.50')
})

test('expense search, category, and inclusive date filters combine and reset', async ({ page }) => {
  await sample(page)
  await nav(page, 'Expenses')
  const rows = page.locator('.record-table').first().locator('tbody tr')
  await expect(rows).toHaveCount(8)
  const log = page.getByRole('heading', { name: 'Expense log', exact: true })
  const comparison = page.locator('summary').filter({ hasText: 'Plan vs recorded by category' })
  expect((await log.boundingBox())!.y).toBeLessThan((await comparison.boundingBox())!.y)
  await page.getByLabel('Search expenses', { exact: true }).fill('ILLUSTRATIVE SAMPLE ENTRY')
  await page.getByRole('combobox', { name: 'Filter by category', exact: true }).selectOption('labor')
  await page.getByLabel('From date', { exact: true }).fill('2026-08-01')
  await page.getByLabel('To date', { exact: true }).fill('2026-10-15')
  await expect(rows).toHaveCount(2)
  await expect(page.getByRole('button', { name: 'Edit Hired field labor', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Edit Harvest labor', exact: true })).toBeVisible()
  await page.getByLabel('Search expenses', { exact: true }).fill('HARVEST')
  await expect(rows).toHaveCount(1)
  await expect(rows).toContainText('Harvest labor')
  await page.getByLabel('Search expenses', { exact: true }).fill('')
  await page.getByLabel('To date', { exact: true }).fill('2026-08-01')
  await expect(rows).toHaveCount(1)
  await expect(rows).toContainText('Hired field labor')
  await page.getByLabel('From date', { exact: true }).fill('2026-09-01')
  await expect(page.getByRole('alert')).toContainText('From date must be on or before the to date.')
  await page.getByRole('button', { name: 'Reset filters', exact: true }).first().click()
  await expect(rows).toHaveCount(8)
  await expect(page.getByLabel('Search expenses', { exact: true })).toHaveValue('')
  await expect(page.getByRole('combobox', { name: 'Filter by category', exact: true })).toHaveValue('all')
  await expect(page.getByLabel('From date', { exact: true })).toHaveValue('')
  await expect(page.getByLabel('To date', { exact: true })).toHaveValue('')
  await expect(page.getByRole('button', { name: 'Reset filters', exact: true })).toBeDisabled()
})

test('dirty expense dismissal keeps inputs and traps focus until explicitly discarded', async ({ page }) => {
  await sample(page)
  await page.getByRole('button', { name: 'Add expense', exact: true }).click()
  const form = page.getByRole('dialog', { name: 'Add expense', exact: true })
  await form.getByLabel('Expense name', { exact: true }).fill('Do not lose this fuel')
  await form.getByLabel('Amount paid or valued (₱)', { exact: false }).fill('87.25')
  await page.keyboard.press('Escape')
  const confirmation = discardDialog(page)
  await expect(confirmation).toBeVisible()
  await expect(confirmation.getByRole('button', { name: 'Keep editing', exact: true })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(confirmation.getByRole('button', { name: 'Discard changes', exact: true })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(confirmation.getByRole('button', { name: 'Keep editing', exact: true })).toBeFocused()
  await confirmation.getByRole('button', { name: 'Keep editing', exact: true }).click()
  await expect(confirmation).toHaveCount(0)
  await expect(form.getByLabel('Expense name', { exact: true })).toHaveValue('Do not lose this fuel')
  await expect(form.getByLabel('Amount paid or valued (₱)', { exact: false })).toHaveValue('87.25')
  await form.getByRole('button', { name: 'Close / Isara', exact: true }).click()
  await confirmation.getByRole('button', { name: 'Discard changes', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect.poll(() => page.evaluate(() => document.body.style.overflow)).not.toBe('hidden')
  await expect(page.getByRole('button', { name: 'Edit Do not lose this fuel', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Add expense', exact: true }).click()
  await expect(form.getByLabel('Expense name', { exact: true })).toHaveValue('')
  await form.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('scenario drafts protect navigation and preset replacement, including a second edit', async ({ page }) => {
  await sample(page)
  await nav(page, 'Scenarios')
  await page.getByLabel('Scenario name', { exact: true }).fill('My careful scenario')
  await nav(page, 'Reports')
  await discardDialog(page).getByRole('button', { name: 'Keep editing', exact: true }).click()
  await expect(page).toHaveURL(/#scenarios$/)
  await expect(page.getByLabel('Scenario name', { exact: true })).toHaveValue('My careful scenario')
  await page.getByRole('button', { name: /A smaller harvest/ }).click()
  await discardDialog(page).getByRole('button', { name: 'Discard changes', exact: true }).click()
  await expect(page.getByLabel('Scenario name', { exact: true })).toHaveValue('Lower harvest')
  await expect(page.getByRole('spinbutton', { name: 'Harvest quantity %', exact: true })).toHaveValue('-10')
  await page.getByRole('spinbutton', { name: 'Input costs %', exact: true }).fill('25')
  await nav(page, 'Reports')
  await expect(discardDialog(page)).toBeVisible()
  await discardDialog(page).getByRole('button', { name: 'Keep editing', exact: true }).click()
  await expect(page.getByRole('spinbutton', { name: 'Input costs %', exact: true })).toHaveValue('25')
  await nav(page, 'Reports')
  await discardDialog(page).getByRole('button', { name: 'Discard changes', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Reports', exact: true })).toBeVisible()
  await nav(page, 'Scenarios')
  await expect(page.getByRole('spinbutton', { name: 'Input costs %', exact: true })).toHaveValue('10')
  await page.getByLabel('Scenario name', { exact: true }).fill('Saved draft')
  await page.getByRole('button', { name: 'Save this scenario', exact: true }).click()
  await expect(page.getByRole('button', { name: /^Saved draft Saved baseline/ })).toBeVisible()
  await nav(page, 'Overview')
  await expect(discardDialog(page)).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Every season, a clearer plan.' })).toBeVisible()
})

test('opening a new season protects scenario edits and discarded drafts reset beneath the dialog', async ({ page }) => {
  await sample(page)
  await nav(page, 'Scenarios')
  await page.getByLabel('Scenario name', { exact: true }).fill('Protect before new season')
  await page.getByRole('button', { name: 'New season', exact: true }).click()
  await discardDialog(page).getByRole('button', { name: 'Keep editing', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByLabel('Scenario name', { exact: true })).toHaveValue('Protect before new season')
  await page.getByRole('button', { name: 'New season', exact: true }).click()
  await discardDialog(page).getByRole('button', { name: 'Discard changes', exact: true }).click()
  const seasonForm = page.getByRole('dialog', { name: 'Start a new season', exact: true })
  await expect(seasonForm).toBeVisible()
  await seasonForm.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByLabel('Scenario name', { exact: true })).toHaveValue('Higher input costs')
  await page.getByRole('spinbutton', { name: 'Input costs %', exact: true }).fill('35')
  await nav(page, 'Reports')
  await expect(discardDialog(page)).toBeVisible()
  await discardDialog(page).getByRole('button', { name: 'Discard changes', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Reports', exact: true })).toBeVisible()
})

test('switching seasons asks before discarding a scenario and keeps the original selection on cancellation', async ({ page }) => {
  await sample(page)
  const selector = page.getByLabel('Active season', { exact: true })
  const sampleId = await selector.inputValue()
  await page.getByRole('button', { name: 'New season', exact: true }).click()
  const form = page.getByRole('dialog', { name: 'Start a new season', exact: true })
  await form.getByLabel('Farm nickname', { exact: true }).fill('Scenario continuity farm')
  await form.getByLabel('Season name', { exact: true }).fill('Other season')
  await form.getByRole('button', { name: 'Save season', exact: true }).click()
  await expect(form).toHaveCount(0)
  const otherId = await selector.inputValue()
  expect(otherId).not.toBe(sampleId)
  await selector.selectOption(sampleId)
  await nav(page, 'Scenarios')
  await page.getByLabel('Scenario name', { exact: true }).fill('Stay on my sample')
  await selector.selectOption(otherId)
  await discardDialog(page).getByRole('button', { name: 'Keep editing', exact: true }).click()
  await expect(selector).toHaveValue(sampleId)
  await expect(page.getByLabel('Scenario name', { exact: true })).toHaveValue('Stay on my sample')
  await selector.selectOption(otherId)
  await discardDialog(page).getByRole('button', { name: 'Discard changes', exact: true }).click()
  await expect(selector).toHaveValue(otherId)
  await expect(page.getByLabel('Scenario name', { exact: true })).toHaveValue('Higher input costs')
  await page.getByLabel('Scenario name', { exact: true }).fill('Other season unsaved')
  await selector.selectOption(sampleId)
  await expect(discardDialog(page)).toBeVisible()
  await discardDialog(page).getByRole('button', { name: 'Discard changes', exact: true }).click()
  await expect(selector).toHaveValue(sampleId)
})

test('actual conditions remain unknown until confirmed and are independent of planned conditions', async ({ page }) => {
  await sample(page)
  await nav(page, 'Expenses')
  await page.getByRole('checkbox', { name: /I have entered every expense for this season/ }).click()
  await expect(page.getByRole('checkbox', { name: /I have entered every expense for this season/ })).toBeChecked()
  await expect(page.getByText('Expense completeness updated.', { exact: true })).toBeVisible()
  await nav(page, 'Reports')
  const recorded = page.locator('section').filter({ has: page.getByRole('heading', { name: 'Recorded outcome', exact: true }) })
  const value = recorded.locator('.stat-card').filter({ hasText: 'Production value' }).locator('strong')
  const returns = recorded.locator('.stat-card').filter({ hasText: 'Recorded full-cost return' }).locator('strong')
  await page.getByRole('button', { name: 'Edit actual harvest', exact: true }).click()
  const form = page.getByRole('dialog', { name: 'Actual harvest and price', exact: true })
  await expect(form.getByRole('combobox', { name: 'Actual harvest condition', exact: true })).toHaveValue('')
  await expect(form.getByRole('combobox', { name: 'Actual price condition', exact: true })).toHaveValue('')
  await form.getByLabel('Actual harvested kg', { exact: false }).fill('4000')
  await form.getByLabel('Actual farmgate price per kg (₱)', { exact: false }).fill('20')
  await form.getByRole('button', { name: 'Save actual result', exact: true }).click()
  await expect(value).toHaveText('—')
  await expect(returns).toHaveText('—')
  await page.getByRole('button', { name: 'Edit actual harvest', exact: true }).click()
  await form.getByRole('combobox', { name: 'Actual harvest condition', exact: true }).selectOption('dried')
  await form.getByRole('combobox', { name: 'Actual price condition', exact: true }).selectOption('fresh')
  await form.getByRole('button', { name: 'Save actual result', exact: true }).click()
  await expect(value).toHaveText('—')
  await expect(returns).toHaveText('—')
  await page.getByRole('button', { name: 'Edit actual harvest', exact: true }).click()
  await form.getByRole('combobox', { name: 'Actual price condition', exact: true }).selectOption('dried')
  await form.getByRole('button', { name: 'Save actual result', exact: true }).click()
  await expect(value).toHaveText('₱80,000.00')
  await expect(returns).toHaveText('₱26,000.00')
  const identity = page.getByRole('region', { name: 'Report identity', exact: true })
  await expect(identity).toContainText('Harvest: Fresh palay · Price: Fresh palay')
  await expect(identity).toContainText('Harvest: Dried palay · Price: Dried palay')
  await page.reload()
  await expect(returns).toHaveText('₱26,000.00')
  await page.getByRole('button', { name: 'Edit actual harvest', exact: true }).click()
  await expect(form.getByRole('combobox', { name: 'Actual harvest condition', exact: true })).toHaveValue('dried')
  await expect(form.getByRole('combobox', { name: 'Actual price condition', exact: true })).toHaveValue('dried')
})

test('report identity, detailed CSV and printed ledgers retain evidence and hide controls', async ({ page }, info) => {
  await sample(page)
  await nav(page, 'Reports')
  const identity = page.getByRole('region', { name: 'Report identity', exact: true })
  await expect(identity).toContainText('Sample farm — San Isidro')
  await expect(identity).toContainText('Sample wet season 2026')
  await expect(identity).toContainText('Sample — illustrative data')
  await expect(identity).toContainText('Report date:')
  await expect(identity).toContainText('Harvest: Unknown · Price: Unknown')
  await expect(page.getByRole('heading', { name: 'Planned cost ledger', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Recorded expense ledger', exact: true })).toBeVisible()
  const pending = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export CSV', exact: true }).click()
  const file = await pending
  expect(file.suggestedFilename()).toMatch(/^PaSiBudget-report-.*\.csv$/)
  const csv = await readFile((await file.path())!, 'utf8')
  for (const text of ['Sample farm — San Isidro', 'Sample wet season 2026', 'Sample — illustrative data', 'Report date', 'Actual harvest condition', 'Unknown', 'Planned cost ledger', 'Recorded expense ledger', 'Certified seed', 'Evidence', 'Notes', 'Illustrative sample entry, not a verified farm record.', 'All recorded expenses entered', 'Known items only']) expect(csv).toContain(text)
  expect(csv).toContain('"Certified seed","Seeds","Cash","Fixed season total","8000","8000"')
  expect(csv).toContain('"2026-06-10","Certified seed","Seeds","Cash","8000"')
  await page.emulateMedia({ media: 'print' })
  await expect(identity).toBeVisible()
  await expect(page.getByRole('button', { name: 'Export CSV', exact: true })).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Edit actual harvest', exact: true })).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Download backup', exact: true })).not.toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Main navigation', exact: true })).not.toBeVisible()
  await expect(page.locator('.report-ledger').first().locator('thead')).toHaveCSS('display', 'table-header-group')
  await expect(page.locator('.report-ledger').nth(1)).toContainText('Illustrative sample entry, not a verified farm record.')
  await page.pdf({ path: info.outputPath('sample-season-report.pdf'), format: 'A4', printBackground: true })
})

for (const width of [360, 390, 768, 1440]) {
  for (const language of ['en', 'fil'] as const) {
    for (const theme of ['light', 'dark'] as const) {
      test(`responsive ${width}px ${language} ${theme}: navigation, cards and readable controls`, async ({ page }, info) => {
        await page.setViewportSize({ width, height: width > 800 ? 1050 : 900 })
        await page.emulateMedia({ reducedMotion: 'reduce' })
        await sample(page)
        if (language === 'fil') await page.getByRole('button', { name: 'Switch to Filipino', exact: true }).click()
        if (theme === 'dark') await page.getByRole('button', { name: language === 'fil' ? 'Isara ang palay · madilim na mode' : 'Close rice grain · switch to dark mode', exact: true }).press('Enter')
        await expect(page.locator('html')).toHaveAttribute('lang', language)
        await expect(page.locator('html')).toHaveAttribute('data-theme', theme)
        const noPageOverflow = async () => expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
        await noPageOverflow()
        await page.screenshot({ path: info.outputPath(`overview-${width}-${language}-${theme}.png`), fullPage: true })
        const links = language === 'fil' ? ['Badyet', 'Mga gastos', 'Mga sitwasyon', 'Mga ulat'] : ['My budget', 'Expenses', 'Scenarios', 'Reports']
        for (const name of links) {
          await nav(page, name, language)
          await noPageOverflow()
          await expect(page.locator('h1')).toBeVisible()
          if (name === 'My budget' || name === 'Badyet' || name === 'Expenses' || name === 'Mga gastos') {
            const table = page.locator('.record-table').first()
            if (width <= 800) {
              await expect(table.locator('thead')).not.toBeVisible()
              await expect(table.locator('tbody tr').first()).toHaveCSS('display', 'block')
              await expect(table.locator('tbody td').first()).toHaveAttribute('data-label', /.+/)
            } else await expect(table.locator('thead')).toBeVisible()
          }
        }
        await nav(page, language === 'fil' ? 'Mga gastos' : 'Expenses', language)
        await page.getByRole('button', { name: language === 'fil' ? 'Magdagdag ng gastos' : 'Add expense', exact: true }).click()
        const form = page.getByRole('dialog')
        const input = form.getByLabel(language === 'fil' ? 'Pangalan ng gastos' : 'Expense name', { exact: true })
        expect(await input.evaluate(el => parseFloat(getComputedStyle(el).fontSize))).toBeGreaterThanOrEqual(16)
        const save = form.getByRole('button', { name: language === 'fil' ? 'I-save ang gastos' : 'Save expense', exact: true })
        expect((await save.boundingBox())!.height).toBeGreaterThanOrEqual(44)
        await expect(form.locator('.field small').first()).toHaveCSS('font-size', '14px')
        await form.getByRole('button', { name: 'Close / Isara', exact: true }).click()
        expect(await page.locator('.rice-lid').evaluate(el => getComputedStyle(el).transitionDuration)).toBe('0s')
        if (width === 390 && language === 'fil') await page.screenshot({ path: info.outputPath(`expense-cards-${theme}.png`), fullPage: true })
      })
    }
  }
}

test('200 percent equivalent reflow retains access to forms and mobile navigation', async ({ page }, info) => {
  await page.setViewportSize({ width: 1440, height: 1050 })
  await sample(page)
  // Browser zoom reduces the layout viewport. Half the width and height of
  // 1440x1050 exercises 200% reflow without relying on browser chrome shortcuts.
  await page.setViewportSize({ width: 720, height: 525 })
  await nav(page, 'Expenses')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
  await page.getByRole('button', { name: 'Add expense', exact: true }).click()
  const form = page.getByRole('dialog', { name: 'Add expense', exact: true })
  await form.getByLabel('Expense name', { exact: true }).fill('Zoom keyboard entry')
  await form.getByRole('button', { name: 'Save expense', exact: true }).click()
  await expect(form).toHaveCount(0)
  await expect(page.getByRole('row').filter({ hasText: 'Zoom keyboard entry' })).toBeVisible()
  await page.screenshot({ path: info.outputPath('zoom-200-percent.png'), fullPage: true })
})
