import { ArrowUpRight, ArrowRight, Plus, Wallet, CircleDollarSign, Wheat, TrendingUp, Check, AlertCircle, Sprout, CalendarDays } from 'lucide-react'
import { calculateBudget, seasonInput } from '../lib/calculations'
import { categoryLabel, money, number, tr, kindLabel } from '../lib/format'
import { FarmLandscape } from '../components/Rice'
import { categories } from '../types'
import type { PageProps } from '../types'
import Decimal from 'decimal.js'

export default function OverviewPage({ data, season, lang, navigate, editSeason }: PageProps & { navigate: (page: string) => void; editSeason: () => void }) {
  const items = data.budgetItems.filter(i => i.seasonId === season.id)
  const expenses = data.expenses.filter(e => e.seasonId === season.id)
  const calc = calculateBudget(seasonInput(season, items))
  const spent = expenses.filter(e => e.kind === 'cash' && e.amount !== null).reduce((sum, e) => sum.plus(e.amount!), new Decimal(0)).toNumber()
  const farm = data.farms.find(f => f.id === season.farmId)!
  const receipts = data.receipts.filter(r => r.seasonId === season.id).reduce((sum, r) => sum.plus(r.amount), new Decimal(0)).toNumber()
  const costCategories = categories.map(category => ({ category, value: expenses.filter(e => e.category === category && e.kind === 'cash' && e.amount != null).reduce((sum, e) => sum.plus(e.amount!), new Decimal(0)).toNumber() })).filter(c => c.value > 0).sort((a,b) => b.value-a.value)
  const totalCosts = costCategories.reduce((sum, c) => sum+c.value, 0)
  const colors = ['#2e7758','#a0b895','#dcba67','#718e81','#c5c9b1','#bd9d79','#91a078','#859b8e','#d5d8c8']
  let offset = 0
  const segments = costCategories.map((c,i) => { const start=offset; offset += c.value/totalCosts*100; return `${colors[i]} ${start}% ${offset}%` })
  const harvestDate = season.harvestDate ? new Date(`${season.harvestDate}T12:00:00`).toLocaleDateString(lang === 'fil' ? 'fil-PH' : 'en-PH', { month: 'short', day: 'numeric', year: 'numeric' }) : tr(lang, 'Not set yet', 'Hindi pa naitakda')
  return <>
    <div className="page-heading overview-heading"><div><div className="eyebrow">{tr(lang, 'YOUR FARM, AT A GLANCE', 'ISANG SULYAP SA IYONG SAKAHAN')}</div><h1>{tr(lang, 'Every season, a clearer plan.', 'Mas malinaw na plano sa bawat taniman.')}</h1><p className="muted">{tr(lang, 'A little clarity today. More confidence for the harvest.', 'Linaw sa pagpaplano ngayon. Kumpiyansa sa darating na ani.')}</p></div><button className="button primary" onClick={() => navigate('expenses')}><Plus size={17}/>{tr(lang, 'Add expense', 'Magtala ng gastos')}</button></div>
    <section className="season-hero"><FarmLandscape className="hero-landscape"/><div className="hero-copy"><div className="hero-season"><span className="status-dot"/>{tr(lang, 'YOUR GROWING SEASON', 'IYONG KASALUKUYANG TANIMAN')}</div><h2>{season.name}</h2><p>{farm.name} <span>·</span> {number(season.areaHa===null?null:Number(season.areaHa), 2)} {tr(lang, 'hectares', 'ektarya')} <span>·</span> {farm.location}</p><div className="hero-details"><span><Sprout size={15}/>{season.grainCondition === 'fresh' ? tr(lang, 'Fresh palay', 'Basang palay') : tr(lang, 'Dried palay', 'Tuyong palay')}</span><span><CalendarDays size={15}/>{tr(lang, 'Harvest', 'Ani')} {harvestDate}</span></div><button className="hero-button" onClick={editSeason}>{tr(lang, 'View season details', 'Detalye ng taniman')}<ArrowUpRight size={16}/></button></div></section>
    <div className="metrics-grid">
      <Metric icon={<Wallet size={19}/>} label={tr(lang, 'Planned cash budget', 'Planong salaping badyet')} value={money(calc.cash.knownTotal)} note={calc.cash.complete ? tr(lang, 'Cash costs for this season', 'Salaping gastos ngayong taniman') : tr(lang, 'Known subtotal · incomplete', 'Alam na subtotal · kulang')} accent="green"/>
      <Metric icon={<CircleDollarSign size={19}/>} label={tr(lang, 'Cash expenses recorded', 'Naitalang salaping gastos')} value={money(spent)} note={tr(lang, `${expenses.length} entries · recorded so far`, `${expenses.length} tala · hanggang ngayon`)} accent="gold"/>
      <Metric icon={<Wheat size={19}/>} label={tr(lang, 'Estimated production value', 'Tinatayang halaga ng ani')} value={money(calc.productionValue)} note={tr(lang, 'Harvest × assumed price · not cash received', 'Ani × palagay na presyo · hindi natanggap na pera')} accent="sage"/>
      <Metric icon={<TrendingUp size={19}/>} label={tr(lang, 'Full-cost break-even price', 'Presyong bawi ang buong gastos')} value={money(calc.full.breakEvenPrice)} suffix="/ kg" note={tr(lang, 'Includes non-cash & imputed costs', 'Kasama ang di-salaping at tinatayang gastos')} accent="peach"/>
    </div>
    <div className="dashboard-columns"><section className="card spending-card"><div className="card-header"><div><h2>{tr(lang, 'Where your money goes', 'Saan napupunta ang gastos')}</h2><p className="muted">{tr(lang, 'Your recorded cash expenses, by category', 'Naitalang salaping gastos ayon sa kategorya')}</p></div><button className="text-button" onClick={() => navigate('expenses')}>{tr(lang, 'View all', 'Lahat')}<ArrowUpRight size={16}/></button></div><div className="spending-body"><div className="donut" style={{background: segments.length ? `conic-gradient(${segments.join(',')})` : 'var(--border)'}} role="img" aria-label={tr(lang, 'Cash spending by category', 'Salaping gastos ayon sa kategorya')}><div className="donut-center"><span>{tr(lang, 'TOTAL SPENT', 'KABUUANG GASTOS')}</span><strong>{money(spent)}</strong><small>{tr(lang, 'cash expenses', 'salaping gastos')}</small></div></div><div className="chart-legend">{costCategories.length ? costCategories.slice(0,5).map((c,i) => <div key={c.category}><span className="legend-dot" style={{background:colors[i]}}/><span>{categoryLabel(c.category,lang)}</span><strong>{money(c.value)}</strong><small>{Math.round(c.value/totalCosts*100)}%</small></div>) : <p className="muted">{tr(lang, 'Your spending breakdown appears after your first cash expense.', 'Makikita ang pagkakahati ng gastos matapos ang unang salaping tala.')}</p>}{costCategories.length>5 && <button className="text-button" onClick={() => navigate('expenses')}>{tr(lang, '+ More categories', '+ Iba pang kategorya')}<ArrowRight size={14}/></button>}</div></div><div className="card-footer"><span className="small-dot"/>{tr(lang, 'Based on your records. Blank amounts are still unknown.', 'Batay sa iyong tala. Hindi pa alam ang blangkong halaga.')}</div></section>
    <section className="card harvest-card"><div className="card-header"><div><h2>{tr(lang, 'Your harvest outlook', 'Tanaw sa iyong ani')}</h2><p className="muted">{tr(lang, 'A plan, with your assumptions', 'Plano batay sa iyong mga palagay')}</p></div><span className="icon-tile sage"><Sprout size={20}/></span></div><dl className="outlook-list"><div><dt>{tr(lang, 'Expected harvest', 'Inaasahang ani')}</dt><dd>{number(calc.quantityKg,2)} <small>kg</small></dd></div><div><dt>{tr(lang, 'Assumed price', 'Palagay na presyo')}</dt><dd>{money(calc.pricePerKg)} <small>/ kg</small></dd></div><div><dt>{tr(lang, 'Full production cost', 'Buong gastos sa produksyon')}</dt><dd>{money(calc.full.knownTotal)}{!calc.full.complete && <small> *</small>}</dd></div><div className="return-row"><dt>{tr(lang, 'Estimated net return', 'Tinatayang netong kita')}</dt><dd className={calc.full.estimatedReturn != null && calc.full.estimatedReturn < 0 ? 'negative' : 'positive'}>{money(calc.full.estimatedReturn)}</dd></div></dl><div className="outlook-note">{calc.full.complete && calc.productionValue !== null ? <Check size={16}/> : <AlertCircle size={16}/>}<span>{calc.full.complete && calc.productionValue !== null ? tr(lang, 'An estimate, not a guarantee. Explore what changes below.', 'Tantiya, hindi garantiya. Subukan ang mga pagbabago.') : tr(lang, 'Complete your costs and matching harvest assumptions to see results.', 'Kumpletuhin ang gastos at tugmang palagay sa ani upang makita ang resulta.')}</span></div><button className="button secondary full-width" onClick={() => navigate('scenarios')}>{tr(lang, 'Explore what-if scenarios', 'Subukan ang mga sitwasyon')}<ArrowRight size={16}/></button></section></div>
    <div className="dashboard-columns lower-row"><section className="card"><div className="card-header"><div><h2>{tr(lang, 'Recent expenses', 'Mga bagong gastos')}</h2><p className="muted">{tr(lang, 'The little details that add up', 'Bawat detalye ay mahalaga')}</p></div><button className="text-button" onClick={() => navigate('expenses')}>{tr(lang, 'View all', 'Lahat')}<ArrowUpRight size={16}/></button></div><div className="recent-list">{expenses.length ? [...expenses].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3).map(e => <div className="recent-entry" key={e.id}><span className="expense-icon"><Sprout size={18}/></span><div><strong>{e.name}</strong><small>{categoryLabel(e.category,lang)} · {kindLabel(e.kind,lang)} · {e.date}</small></div><strong>{e.amount === null ? tr(lang, 'Unknown', 'Hindi alam') : money(Number(e.amount))}</strong></div>) : <div className="compact-empty">{tr(lang, 'No expenses yet. Start with your first entry.', 'Wala pang gastos. Idagdag ang unang tala.')}</div>}</div></section><section className="tip-card"><span className="eyebrow"><span className="small-dot"/>{tr(lang, 'A LITTLE FARM WISDOM', 'PAALALA SA PAGPAPLANO')}</span><h3>{tr(lang, 'Know your costs. Grow your confidence.', 'Alamin ang gastos. Magplano nang may kumpiyansa.')}</h3><p>{tr(lang, 'Family labor and your own equipment have value, too. Include them to see the full picture of your season.', 'May halaga rin ang paggawa ng pamilya at sariling kagamitan. Isama ang mga ito para sa buong larawan ng gastos.')}</p><button className="text-button" onClick={() => navigate('budget')}>{tr(lang, 'Review your budget', 'Suriin ang badyet')}<ArrowRight size={15}/></button></section></div>
    <div className="overview-footnote"><span>{tr(lang, 'Actual money received', 'Aktuwal na natanggap na pera')}: <strong>{money(receipts)}</strong></span><span>{tr(lang, 'Based on your recorded receipts, separate from production value.', 'Batay sa naitalang resibo, hiwalay sa halaga ng ani.')}</span></div>
  </>
}
function Metric({icon,label,value,note,accent,suffix}:{icon:React.ReactNode;label:string;value:string;note:string;accent:string;suffix?:string}) {
  return <section className="metric-card"><div className="metric-top"><span>{label}</span><span className={`icon-tile ${accent}`}>{icon}</span></div><div className="metric-value">{value}<small>{suffix}</small></div><p>{note}</p></section>
}
