import { useMemo, useState } from 'react'
import { ArrowDown, ArrowUp, ArrowRight, Bookmark, Check, SlidersHorizontal, Trash2, TrendingDown, Wheat } from 'lucide-react'
import { calculateBudget, calculateScenario, seasonInput } from '../lib/calculations'
import { db } from '../lib/db'
import { money, number, tr, uid } from '../lib/format'
import { PageHeading, Field } from '../components/UI'
import type { PageProps, Scenario, BudgetResult } from '../types'

export default function ScenariosPage({data,season,lang,onSave}:PageProps) {
  const [selectedId,setSelectedId] = useState('')
  const [name,setName] = useState(tr(lang,'Higher input costs','Mas mataas na gastos'))
  const [cost,setCost] = useState('10'), [quantity,setQuantity] = useState('0'), [price,setPrice] = useState('0')
  const [error,setError] = useState(''), [busy,setBusy] = useState(false)
  const saved = data.scenarios.filter(s=>s.seasonId===season.id)
  const selected = saved.find(s=>s.id===selectedId)
  const liveBaseline = useMemo(()=>seasonInput(season,data.budgetItems.filter(i=>i.seasonId===season.id)),[season,data.budgetItems])
  const baseline = selected?.baseline || liveBaseline
  const valid = [cost,quantity,price].every(v=>/^-?\d+(?:\.\d+)?$/.test(v) && Number.isFinite(Number(v)) && Number(v)>=-100 && Number(v)<=1000)
  const draft:Scenario = { id:selectedId||'draft',seasonId:season.id,name:name.trim(),baseline,costChangePercent:cost,quantityChangePercent:quantity,priceChangePercent:price,createdAt:selected?.createdAt||new Date().toISOString() }
  const baseResult = calculateBudget(baseline)
  const result = valid ? calculateScenario(draft) : null
  const preset = (kind:string) => {setSelectedId('');setError('');setCost(kind==='cost'?'10':'0');setQuantity(kind==='harvest'?'-10':'0');setPrice(kind==='price'?'-10':'0');setName(kind==='cost'?tr(lang,'Higher input costs','Mas mataas na gastos'):kind==='harvest'?tr(lang,'Lower harvest','Mas mababang ani'):tr(lang,'Lower selling price','Mas mababang presyo'))}
  const load = (s:Scenario) => {setSelectedId(s.id);setName(s.name);setCost(s.costChangePercent);setQuantity(s.quantityChangePercent);setPrice(s.priceChangePercent);setError('')}
  const save = async () => { if(!valid||!name.trim()){setError(tr(lang,'Name your scenario and use changes between −100% and +1,000%.','Pangalanan ang sitwasyon at gumamit ng pagbabago mula −100% hanggang +1,000%.'));return} setBusy(true);const id=selectedId||uid();const ok=await onSave(()=>db.scenarios.put({...draft,id,baseline:structuredClone(baseline)}),tr(lang,'Scenario saved with its baseline.','Na-save ang sitwasyon at batayang badyet.'));setBusy(false);if(ok)setSelectedId(id) }
  const delta = result?.full.estimatedReturn!=null && baseResult.full.estimatedReturn!=null ? result.full.estimatedReturn-baseResult.full.estimatedReturn : null
  return <>
    <PageHeading eyebrow={tr(lang,'EXPLORE THE POSSIBILITIES','SURIIN ANG MGA POSIBILIDAD')} title={tr(lang,'A little “what if” goes a long way.','Subukan ang “paano kung”.')} description={tr(lang,'Change the assumptions. Understand the difference before making a decision.','Baguhin ang mga palagay. Unawain ang epekto bago magpasya.')} actions={<span className="badge gold"><SlidersHorizontal size={14}/>{tr(lang,'What-if calculations · not forecasts','Mga kalkulasyong paano-kung · hindi hula')}</span>}/>
    <div className="scenario-presets"><button className={!selectedId&&cost==='10'&&quantity==='0'&&price==='0'?'preset active':'preset'} onClick={()=>preset('cost')}><span className="icon-tile gold"><ArrowUp size={20}/></span><span><strong>{tr(lang,'Costs go up','Tumaas ang gastos')}</strong><small>{tr(lang,'Input costs +10%','Mga gastos +10%')}</small></span><ArrowRight size={17}/></button><button className={!selectedId&&quantity==='-10'?'preset active':'preset'} onClick={()=>preset('harvest')}><span className="icon-tile sage"><Wheat size={20}/></span><span><strong>{tr(lang,'A smaller harvest','Mas kaunting ani')}</strong><small>{tr(lang,'Harvest quantity −10%','Dami ng ani −10%')}</small></span><ArrowRight size={17}/></button><button className={!selectedId&&price==='-10'?'preset active':'preset'} onClick={()=>preset('price')}><span className="icon-tile peach"><TrendingDown size={20}/></span><span><strong>{tr(lang,'Prices go down','Bumaba ang presyo')}</strong><small>{tr(lang,'Selling price −10%','Presyo ng benta −10%')}</small></span><ArrowRight size={17}/></button></div>
    <div className="scenario-layout"><section className="card scenario-editor"><div className="card-header"><div><h2>{tr(lang,'Make it your scenario','Iangkop ang sitwasyon')}</h2><p className="muted">{tr(lang,'Start with an example, then adjust.','Magsimula sa halimbawa, saka baguhin.')}</p></div></div><div className="section-gap"><Field label={tr(lang,'Scenario name','Pangalan ng sitwasyon')}><input value={name} maxLength={100} onChange={e=>setName(e.target.value)}/></Field><ChangeField label={tr(lang,'Input costs','Mga gastos')} value={cost} onChange={setCost} lang={lang}/><ChangeField label={tr(lang,'Harvest quantity','Dami ng ani')} value={quantity} onChange={setQuantity} lang={lang}/><ChangeField label={tr(lang,'Selling price','Presyo ng benta')} value={price} onChange={setPrice} lang={lang}/><p className="field-hint">{tr(lang,'Cost changes apply to fixed amounts and per-kg rates. Per-kg expenses also adjust to the new harvest quantity.','Ang pagbabago ng gastos ay para sa nakapirming halaga at singil bawat kilo. Inaangkop din ang bawat-kilong gastos sa bagong dami ng ani.')}</p>{error&&<p role="alert" className="negative">{error}</p>}<button className="button primary full-width" disabled={busy} onClick={()=>void save()}><Bookmark size={17}/>{selected?tr(lang,'Save changes','I-save ang pagbabago'):tr(lang,'Save this scenario','I-save ang sitwasyon')}</button></div></section>
    <section className="card scenario-results"><div className="card-header"><div><h2>{tr(lang,'See the difference','Tingnan ang pagkakaiba')}</h2><p className="muted">{selected ? tr(lang,`Compared with the saved baseline from ${selected.createdAt.slice(0,10)}`,`Batay sa na-save na badyet noong ${selected.createdAt.slice(0,10)}`) : tr(lang,'Compared with your current planned budget','Inihahambing sa iyong kasalukuyang badyet')}</p></div></div><div className="scenario-comparison"><div><span className="eyebrow">{tr(lang,'BASELINE RETURN','BATAYANG NETONG KITA')}</span><strong>{money(baseResult.full.estimatedReturn)}</strong><small>{tr(lang,'After full production costs','Matapos ang buong gastos')}</small></div><ArrowRight size={22}/><div className="scenario-highlight"><span className="eyebrow">{tr(lang,'SCENARIO RETURN','NETONG KITA SA SITWASYON')}</span><strong className={result?.full.estimatedReturn!=null&&result.full.estimatedReturn<0?'negative':'positive'}>{money(result?.full.estimatedReturn)}</strong><small>{delta===null?tr(lang,'Complete the baseline first','Kumpletuhin muna ang badyet'):`${delta>=0?'+':''}${money(delta)} ${tr(lang,'vs. baseline','kumpara sa batayan')}`}</small></div></div>
    <div className="table-wrap"><table className="data-table"><thead><tr><th>{tr(lang,'Measure','Sukatan')}</th><th>{tr(lang,'Baseline','Batayan')}</th><th>{tr(lang,'Scenario','Sitwasyon')}</th></tr></thead><tbody><ResultRow label={tr(lang,'Harvest quantity','Dami ng ani')} baseline={`${number(baseResult.quantityKg,2)} kg`} scenario={`${number(result?.quantityKg,2)} kg`}/><ResultRow label={tr(lang,'Price per kilogram','Presyo bawat kilo')} baseline={money(baseResult.pricePerKg)} scenario={money(result?.pricePerKg)}/><ResultRow label={tr(lang,'Production value','Halaga ng ani')} baseline={money(baseResult.productionValue)} scenario={money(result?.productionValue)}/><ResultRow label={tr(lang,'Cash costs (known subtotal)','Salaping gastos (alam na subtotal)')} baseline={money(baseResult.cash.knownTotal)} scenario={money(result?.cash.knownTotal)}/><ResultRow label={tr(lang,'Full costs (known subtotal)','Buong gastos (alam na subtotal)')} baseline={money(baseResult.full.knownTotal)} scenario={money(result?.full.knownTotal)}/><ResultRow label={tr(lang,'Full-cost break-even price','Presyong bawi ang buong gastos')} baseline={money(baseResult.full.breakEvenPrice)} scenario={money(result?.full.breakEvenPrice)}/><ResultRow label={tr(lang,'Full-cost break-even harvest','Aninang bawi ang buong gastos')} baseline={quantityResult(baseResult,lang)} scenario={result?quantityResult(result,lang):'—'}/></tbody></table></div>
    <div className="notice"><Check size={17}/><span>{tr(lang,'Your expense records stay unchanged. These are estimates based on your assumptions, not guaranteed outcomes.','Hindi nababago ang iyong tala ng gastos. Mga tantiya ito batay sa iyong palagay, hindi garantisadong resulta.')}</span></div>{(!baseResult.full.complete||baseResult.productionValue===null||!valid)&&<div className="notice warning">{tr(lang,'Some results are unavailable. Complete all costs, confirm the budget, and use matching harvest and price conditions.','May mga resultang hindi makalkula. Kumpletuhin at kumpirmahin ang badyet at itugma ang kondisyon ng ani at presyo.')}</div>}</section></div>
    {saved.length>0&&<section className="card section-gap saved-scenarios"><div className="card-header"><h2>{tr(lang,'Saved possibilities','Mga na-save na sitwasyon')}</h2><span className="badge">{saved.length}</span></div>{saved.map(s=><div className="saved-scenario" key={s.id}><button onClick={()=>load(s)} className="saved-scenario-link"><Bookmark size={18}/><div><strong>{s.name}</strong><small>{tr(lang,'Saved baseline','Na-save na batayan')} · {s.createdAt.slice(0,10)}</small></div></button><strong>{money(calculateScenario(s).full.estimatedReturn)}</strong><button className="icon-button" aria-label={`${tr(lang,'Delete','Burahin')} ${s.name}`} onClick={()=>{if(confirm(tr(lang,'Delete this saved scenario?','Burahin ang na-save na sitwasyon?')))void onSave(()=>db.scenarios.delete(s.id)).then(ok=>{if(ok&&selectedId===s.id)setSelectedId('')})}}><Trash2 size={16}/></button></div>)}</section>}
  </>
}
function ResultRow({label,baseline,scenario}:{label:string;baseline:string;scenario:string}) {return <tr><td>{label}</td><td className="amount">{baseline}</td><td className="amount">{scenario}</td></tr>}
function quantityResult(result:BudgetResult,lang:PageProps['lang']) {return result.full.breakEvenQuantityStatus==='impossible'?tr(lang,'No finite break-even','Walang maaabot na pagbawi'):result.full.breakEvenQuantity===null?'—':`${number(result.full.breakEvenQuantity,2)} kg`}
function ChangeField({label,value,onChange,lang}:{label:string;value:string;onChange:(v:string)=>void;lang:PageProps['lang']}) {
  return <div className="change-field"><label><span>{label}</span><div className="percent-input"><input type="number" min="-100" max="1000" step="any" value={value} onChange={e=>onChange(e.target.value)}/><span>%</span></div></label><input aria-label={`${label} ${tr(lang,'slider','slider')}`} type="range" min="-100" max="100" step="1" value={Math.min(100,Number(value)||0)} onChange={e=>onChange(e.target.value)}/><div className="range-labels"><span><ArrowDown size={10}/> 100%</span><span>{tr(lang,'No change','Walang pagbabago')}</span><span><ArrowUp size={10}/> 100%</span></div></div>
}
